apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy
  namespace: demo-tekton-cicd
spec:
  workspaces:
    - name: source

  params:
    - name: namespace
      type: string
      description: Namespace to deploy to

    - name: name
      type: string
      description: Name of the application to deploy. ImageStream name should match.

    - name: tag
      type: string
      default: latest
      description: Tag of image to deploy

    - name: gitUrl
      type: string
      default: https://github.com/stocky37/demo-tekton-k8s.git
      description: Git URL of repository that contains k8s resources

  tasks:
    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: $(params.gitUrl)
        - name: deleteExisting
          value: 'true'

    - name: deploy
      taskRef:
        name: deploy
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: source
      params:
        - name: namespace
          value: $(params.namespace)
        - name: name
          value: $(params.name)
        - name: tag
          value: $(params.tag)
