apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy
spec:
  workspaces:
    - name: source

  params:
    - name: gitUrl
      type: string
      description: Git URL of repository that contains k8s resources
      default: https://github.com/stocky37/quarkus-app-k8s.git
    - name: image
      type: string
      description: Name of image to deploy
      default: quarkus-app
    - name: tag
      type: string
      description: Tag of image to deploy
      default: latest

  tasks:
    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: $(params.gitUrl)
        - name: deleteExisting
          value: 'true'

    - name: deploy
      taskRef:
        name: deploy
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: source
      params:
        - name: namespace
          value: example-app
        - name: appImage
          value: $(params.image)
        - name: appTag
          value: $(params.tag)


