apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy
  namespace: demo-tekton-cicd
spec:
  workspaces:
    - name: source

  params:
    - name: app-name
      type: string
      description: application name - imagestream & deployment resources should match

    - name: namespace
      type: string
      description: namespace to deploy to

    - name: tag
      type: string
      default: latest
      description: image tag to deploy

    - name: git-url
      type: string
      default: https://github.com/stocky37/demo-tekton-k8s.git
      description: git url of repository that contains k8s resources

  tasks:
    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: $(params.git-url)
        - name: deleteExisting
          value: 'true'

    - name: deploy
      taskRef:
        name: deploy
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: source
      params:
        - name: namespace
          value: $(params.namespace)
        - name: app-name
          value: $(params.app-name)
        - name: tag
          value: $(params.tag)
