apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: maven
spec:
  workspaces:
    - name: source
    - name: maven-settings

  params:
    - name: gitUrl
      type: string
      description: Git URL of repository to build
      default: https://github.com/stocky37/quarkus-app.git
    - name: namespace
      type: string
      description: Namespace to push image to
      default: example-cicd
    - name: name
      type: string
      description: Name of image to build/push
      default: quarkus-app
    - name: tag
      type: string
      description: Tag of image to build/push
      default: latest
    - name: deployWorkspaceClaim
      type: string
      description: Name of the PVC to use for the deploy pipeline workspace
      default: k8s-src
    - name: deployPipeline
      type: string
      description: Name of the deployment pipeline to kick off
      default: deploy

  tasks:
    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: $(params.gitUrl)
        - name: deleteExisting
          value: 'true'

    - name: maven
      taskRef:
        name: maven
        kind: ClusterTask
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: source
        - name: maven-settings
          workspace: maven-settings
      params:
        - name: GOALS
          value:
            - package
            - -Dquarkus.package.type=fast-jar

    - name: buildah
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
        - maven
      workspaces:
        - name: source
          workspace: source
      params:
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/$(params.namespace)/$(params.name):$(params.tag)
        - name: DOCKERFILE
          value: src/main/docker/Dockerfile.fast-jar
        - name: TLSVERIFY
          value: 'false'

    - name: deploy
      taskRef:
        name: tkn
        kind: ClusterTask
      runAfter:
        - buildah
      params:
        - name: ARGS
          value:
            - pipeline
            - start
            - $(params.deployPipeline)
            - --workspace=name=source,claimName=$(params.deployWorkspaceClaim)
            - --use-param-defaults
