apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-src
  labels:
    app.kubernetes.io/managed-by: apply
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi