apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: demo-listener
  namespace: demo-tekton-cicd
spec:
  serviceAccountName: pipeline
  triggers:
  - name: demo-pipeline-master
    interceptors:
    - github:
        secretRef:
          secretName: github-webhooks
          secretKey: token
        eventTypes:
          - push
    - cel:
        filter: >-
          body.ref == 'refs/head/master'
            && body.repository.name == 'greeting-service-quarkus'
        overlays:
          - key: extensions.short_sha
            expression: body.head_commit.id.truncate(7)
          - key: extensions.app_name
            expression: body.repository.name.replace('-quarkus', '')
    bindings:
    - ref: github-push
      kind: ClusterTriggerBinding
    - ref: github-custom
    template:
      name: maven-pipeline