apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: maven-pipeline
  namespace: demo-tekton-cicd
spec:
  params:
  - name: app-name
    description: name of the application
  - name: git-repo-url
    description: name of the git repository
  - name: git-repo-name
    description: git url to clone
  - name: git-revision
    description: git revision to checkout (branch, tag, sha, ref…)
    default: master
  - name: git-short-revision
    description: git revision truncated to 7 characters
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      labels:
        pipeline: $(tt.params.app-name)
      name: $(tt.params.app-name)-$(tt.params.git-short-revision)-$(uid)
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: maven
      workspaces:
        - name: source
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
              resources:
                requests:
                  storage: 1Gi
        - name: maven-settings
          emptyDir: {}
      params:
      - name: git-url
        value: $(tt.params.git-repo-url)
      - name: git-revision
        value: $(tt.params.git-revision)
      - name: app-name
        value: $(tt.params.app-name)
      - name: deploy-namespace
        value: demo-tekton-app
      - name: deploy-pipeline-prefix
        value: $(tt.params.app-name)-$(tt.params.git-short-revision)-$(uid)-deploy
