apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-custom
  namespace: demo-tekton-cicd
spec:
  params:
  - name: git-short-revision
    value: $(body.extensions.short_sha)
  - name: app-name
    value: $(body.extensions.app_name)
