apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-src
  namespace: demo-tekton-cicd
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 256Mi
