apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: bookinfo
  labels:
    app.kubernetes.io/managed-by: apply
spec:
  serviceAccountName: pipeline
  triggers:
  - interceptors:
    - github:
        secretRef:
          secretName: webhooks
          secretKey: secret
        eventTypes:
          - push
    - cel:
        filter: >-
          body.repository.owner.login == 'tom-stockwell'
            && body.ref == 'refs/head/master'
            && body.repository.name.endsWith('-k8s')
        overlays:
        - key: intercepted.app-name
          expression: "split(body.repository.name, '-')[1]"
        - key: intercepted.git-repo-name
          expression: "split(body.repository.name, '-')[1] + '-' + split(body.repository.name, '-')[2]"
    bindings:
    - name: github-push
      kind: ClusterTriggerBinding
    - name: github-extras
    template:
      name: apply
