---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
spec:
  workspaces:
    - name: source
  params:
    - name: image
      type: string
      description: oc client base image
      default: quay.io/openshift/origin-cli:latest
    - name: resourcesDir
      type: string
      description: directory of k8s resources
      default: "."
    - name: namespace
      type: string
      description: namespace to deploy to
      default: example-app
    - name: appImage
      type: string
      description: Name of image to deploy
      default: quarkus-app
    - name: appTag
      type: string
      description: Tag of image to deploy
      default: latest
    - name: deployment
      type: string
      description: Name of the deployment to wait for rollout
      default: quarkus-app

  steps:
    - name: k8s-resources
      image: $(params.image)
      workingDir: "$(workspaces.source.path)"
      command:
        - /bin/bash
        - -c
      args:
        - >-
          oc apply
          --recursive
          --filename $(params.resourcesDir)
          --namespace $(params.namespace)

    - name: promote-image
      image: $(params.image)
      command:
        - /bin/bash
        - -c
      args:
        - >-
          oc tag
          $(params.appImage):$(params.appTag)
          $(params.namespace)/$(params.appImage):$(params.appTag)

    - name: wait
      image: $(params.image)
      command:
        - /bin/bash
        - -c
      args:
        - >-
          oc rollout status
          deployment/$(params.deployment)
          --watch
          --namespace $(params.namespace)
