---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
spec:
  workspaces:
    - name: source
  params:
    - name: namespace
      type: string
      description: Namespace to deploy to

    - name: name
      type: string
      description: Name of the application to deploy. ImageStream & Deployment resource names should match.

    - name: tag
      type: string
      default: latest
      description: Tag of the image to deploy

    - name: dir
      type: string
      default: "."
      description: Directory of k8s resources to apply

    - name: ocImage
      type: string
      default: quay.io/openshift/origin-cli:latest
      description: OpenShift client image to use

  steps:
    - name: k8s-resources
      image: $(params.ocImage)
      workingDir: "$(workspaces.source.path)"
      command:
        - /bin/bash
        - -c
      args:
        - >-
          oc apply
          --recursive
          --filename $(params.dir)
          --namespace $(params.namespace)

    - name: promote-image
      image: $(params.ocImage)
      command:
        - /bin/bash
        - -c
      args:
        - >-
          oc tag
          $(params.name):$(params.tag)
          $(params.namespace)/$(params.name):$(params.tag)

    - name: wait
      image: $(params.ocImage)
      command:
        - /bin/bash
        - -c
      args:
        - >-
          oc rollout status
          deployment/$(params.name)
          --watch
          --namespace $(params.namespace)
