apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
  namespace: demo-tekton-cicd
spec:
  workspaces:
    - name: source
  params:
    - name: app-name
      type: string
      description: application name - imagestream & deployment resources should match

    - name: namespace
      type: string
      description: namespace to deploy to

    - name: tag
      type: string
      default: latest
      description: image tag to deploy

    - name: k8s-dir
      type: string
      default: "."
      description: k8s resources directory to apply

    - name: oc-image
      type: string
      default: quay.io/openshift/origin-cli:latest
      description: openshift client image

  steps:
    - name: k8s-resources
      image: $(params.oc-image)
      workingDir: "$(workspaces.source.path)"
      command:
        - /bin/bash
        - -c
      args:
        - >-
          oc apply
          --recursive
          --filename $(params.k8s-dir)
          --namespace $(params.namespace)

    - name: promote-image
      image: $(params.oc-image)
      command:
        - /bin/bash
        - -c
      args:
        - >-
          oc tag
          $(params.app-name):$(params.tag)
          $(params.namespace)/$(params.app-name):$(params.tag)

    - name: wait
      image: $(params.oc-image)
      command:
        - /bin/bash
        - -c
      args:
        - >-
          oc rollout status
          deployment/$(params.app-name)
          --watch
          --namespace $(params.namespace)
