apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: oc
  labels:
    app.kubernetes.io/part-of: cicd
    app.kubernetes.io/managed-by: apply
spec:
  workspaces:
  - name: source
    description: The source workspace
  params:
  - name: SCRIPT
    type: string
    description: The OpenShift CLI arguments to run
    default: oc $@
  - name: ARGS
    type: array
    description: The OpenShift CLI arguments to run
    default:
    - help
  steps:
  - name: oc
    image: quay.io/openshift/origin-cli:latest
    script: $(params.SCRIPT)
    workingDir: "$(workspaces.source.path)"
    args:
    - $(params.ARGS)
    
    
