apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ratings
  labels:
    app.kubernetes.io/part-of: cicd
    app.kubernetes.io/managed-by: apply
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi