apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: apply
  labels:
    app.kubernetes.io/part-of: cicd
    app.kubernetes.io/managed-by: apply
spec:
  workspaces:
  - name: source

  params:
  - name: app-name
    type: string
  - name: git-repo-url
    type: string
  - name: git-revision
    type: string
    default: master
  - name: target-namespace
    type: string
    description: Namespace to apply resources into
  - name: resources-dir
    type: string
    description: Location of the resources to apply
    default: '.'

  tasks:
  - name: clone
    taskRef:
      name: git-clone
    params:
    - name: url
      value: $(params.git-repo-url)
    - name: revision
      value: $(params.git-revision)
    - name: deleteExisting
      value: 'true'
    workspaces:
    - name: output
      workspace: source

  - name: apply
    taskRef:
      name: oc-apply-wait
    runAfter: ["clone"]
    params:
    - name: resources
      value: $(params.resources-dir)
    - name: namespace
      value: $(params.target-namespace)
    - name: deployment
      value: dc/$(params.app-name)
    workspaces:
    - name: source
      workspace: source
